### ISSUE TITLE
Timer Integration Fails on 0.103.6

### ISSUE THREAD

**Issue by databoy2k** [e2m32/hass_custom_timer#1]
Had this installed on 0.103.3. Upgraded to 0.103.6. I had a number of timers running with extended long terms and restores. Now the timers refuse to set up.

Traceback:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 406, in _async_add_entity
    await entity.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/timer/__init__.py", line 211, in async_added_to_hass
    int, str(state.attributes.get(ATTR_DURATION)).split(":")
ValueError: invalid literal for int() with base 10: '7 days, 0'
```

configuration.yaml (one of 8)
```
timer:
  chore_vacuum_bedrooms:
    name: "Reset Timer"
    restore_grace_period: '24:00:00'
```

**Comment by databoy2k** [comment]
The workaround was to add "restore: false" to each of the timers and allow them to be reset. But it looks to me (as a complete non-coder) that the issue was in the parsing of the length of the timers.

**Comment by e2m32** [comment]
Thank you @databoy2k. I'll look into it 👍 I haven't tested it on 0.103.6 yet.

**Comment by e2m32** [comment]
I just tested this on 0.103.6 and everything seems to be working fine. The error you shared shows an issue with restoring the set duration. For some reason your last stored duration looks something like `'7 days, 0'` instead of `'168:00:00'` Can you shed any light on this?

**Comment by databoy2k** [comment]
I cannot, sorry. Even my action that starts the timers is for a duration of '168:00:00'. I've done a full find on all of my .yaml files, and nothing sets a 7 day timer.

I can confirm that 168 hours is 7 days; I did that math at one point when coding my automations. Something is apparently converting 168 hours into the number of days, but the component is mis-reading that duration.

**Comment by e2m32** [comment]
@databoy2k I did not anticipate timers greater than 24 hours and assumed that the duration would be saved in HHH:MM:SS... but I did not think to test it. I will work on fixing it, but it's going to be a bit. They made a lot of changes from v0.103 to v0.104 and I'd like to keep this component up to date with the latest release.

**Comment by databoy2k** [comment]
@e2m32 it looked like it. Thanks a ton; I appreciate the help. It's definitely a pain but it's not for something mission critical. Probably a good fix to get in before you get it merged to the master HA (saw your pull request). 

I wish I knew Python to be able to help, but if you've ever seen my help requests on the Discord you'd know you want me as far from your codebase as humanly possible. So I will stay patient. Happy to test fixes if you want, since I've got it running anyways. Good luck and much appreciated.

**Comment by e2m32** [comment]
Ok. This should be fixed with my latest commit, but it includes the changes from 0.105 which hasn't released yet. I tested it on 0.104 and there is a helper file missing. So you can either install the dev branch and update your custom timer, or wait until the 0.105 release.

**Comment by Krocko** [comment]
Can you please tell, how to install the 0.105 dev?

**Comment by e2m32** [comment]
@Krocko it depends on your install.
For Manual Installations:
https://www.home-assistant.io/docs/installation/updating/#run-the-development-version
`pip3 install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev`

For Hassio, I assume that it would be something like this:
`hassio homeassistant update --version 0.105.0b0`
I think you'd have to wait until the beta is released, because the dev branch is never marked as a release. When the beta is released, I believe the above command will work. Watch [here](https://github.com/home-assistant/home-assistant/releases) for the beta release. The beta should be released in the [next few days](https://www.home-assistant.io/blog/2018/03/24/new-release-schedule/). If you don't already have it, you'll need the [SSH Add-on](https://www.home-assistant.io/addons/ssh/) to execute this command.

All that said, I think there are going to be a lot of breaking changes in this release, so if you want to go for it, expect some issues. I would test this on another system before putting it on your main HA 'production version.'

Cheers 🍻

**Comment by databoy2k** [comment]
Necro'ing the closed issue to confirm that the updated version works on 0.105. Thanks a ton - in full support of you merging this into the main HA branch.

**Comment by e2m32** [comment]
Thanks for verifying and for the support @databoy2k! I couldn't get any real guidance on the PR for > 24 hour support so I am moving forward without it for now. 🤷‍♂️I still need to figure our how to write the tests. Then we'll see where we go from there. Thanks again.
